added new constants section, and alphabetised them.
cs-discord-at-ucf/lion pull request #331
Opened 2021-03-26 00:41 UTC by CallumCoy

I think we have grown to the point that we need to split up the channels.  I also think we could benefit if we categorized the channels.

2021-03-26 13:30 UTC, tanndlin commented
Let's finish #329 and #330, then work on this one

2021-03-27 23:41 UTC, tanndlin requested changes
Info should be for read-only channels at the top of the server, so `helpful_baubles` and `club_announcements` should be public, but I see where you are coming from

2021-03-27 23:41 UTC, tanndlin commented on src/common/constants.ts
> +    Info: {
Put these in order as the are in the server, this is kind hard to look at lol

2021-03-27 23:41 UTC, tanndlin commented on src/common/constants.ts
>        General: 'general',
Put `#general` at the top of `public` so that #329 shows it first

2021-03-28 01:50 UTC, tanndlin commented
I meant to put the channels inside of public, as they are in the server, so pretty much how it was before the PR. That was my mistake, I think I put the comment in the wrong spot.

2021-03-28 23:25 UTC, tanndlin approved these changes
lgtm

2021-03-29 12:45 UTC, c650 commented
use of `Info` is fine with me but organising this file doesnt add much value because it's really a ctrl+f file

2021-03-31 17:35 UTC, CallumCoy commented
Are we waiting for me to do something on this pull?

2021-03-31 18:03 UTC, merged