Only allow wolfram alpha and equation plugin in channels under #help
cs-discord-at-ucf/lion pull request #505
Opened 2021-06-25 15:53 UTC by Armintron

2021-06-25 16:39 UTC, tanndlin commented on src/app/plugins/equation.plugin.ts
> +    if (((message.channel as TextChannel).parent as CategoryChannel).name !== 'Help') {
Are you sure the capitalization is correct?
Should probably do `name.toLowerCase() !== 'help'`

2021-06-25 16:39 UTC, tanndlin commented on src/app/plugins/wolframalpha.plugin.ts
> +    if (((message.channel as TextChannel).parent as CategoryChannel).name !== 'Help') {
saa

2021-06-25 16:40 UTC, suneettipirneni requested changes
It would be preferable if a new `ChannelType` like `ChannelType.Help` was introduced so it could used in other plugins down the line.

2021-06-25 16:58 UTC, tanndlin commented
> It would be preferable if a new `ChannelType` like `ChannelType.Help` was introduced so it could used in other plugins down the line.

I thought of that too. Help should be under public as a subset. This PR would need a rename though. Out of scope for this as it stands

2021-06-25 17:16 UTC, Armintron commented
Ill leave this PR as is and make another for making channel subsets

2021-06-29 04:06 UTC, tanndlin commented
I've started coding this, and changing `Constants.ts` is just not worth the added complexity
We can just make a function to compare a string vs channel parent name if anything

2021-07-03 20:03 UTC, tanndlin commented
You can now set a `pluginCategoryName` as of #519
That's all you need to do to solve this PR

2021-07-04 20:21 UTC, merged