Add minRoleToRun to slash commands
cs-discord-at-ucf/lion pull request #792
Opened 2023-09-16 23:31 UTC by tanndlin

Brings back the minRoleToRun functionality of legacy plugins

just a secondary precaution to prevent sensitive commands being used

2023-09-16 23:33 UTC, suneettipirneni commented
We can modify our slash command structure to have a defaultPermission field. This tells discord the minimum permissions a user needs to run a command, and prevents any unsafe window between a command being deployed and an admin setting the perms.

2023-09-16 23:34 UTC, tanndlin commented
> We can modify our slash command structure to have a defaultPermission field. This tells discord the minimum permissions a user needs to run a command, and prevents any unsafe window between a command being deployed and an admin setting the perms.

oh ok perfect, wasnt sure if that was implemented on the API side since the server can set them manually as well

2023-09-17 00:07 UTC, suneettipirneni requested changes

2023-09-17 00:07 UTC, suneettipirneni commented on src/common/slash.ts
> +  minPermissions?: PermissionResolvable;
We can probably use the same discord name for it as it's a bit more accurate.
```suggestion
  defaultMemberPermissions?: PermissionResolvable;
```

2023-09-17 00:07 UTC, suneettipirneni commented on src/common/slash.ts
> +  minRoleToRun: z.optional(z.any()),
This will need to be renamed to the new field name.

2023-09-17 00:41 UTC, suneettipirneni approved these changes

2023-09-17 02:44 UTC, merged