convert alt and leaderboard to slash commands
cs-discord-at-ucf/lion pull request #802
Opened 2023-09-18 18:59 UTC by suneettipirneni

2023-09-19 22:51 UTC, tanndlin requested changes
sorry for the delay

2023-09-19 22:51 UTC, tanndlin commented on src/app/slash_plugins/leaderboard.plugin.ts
> +function getMatchUpEmbed(
one of these is marked async, one is not. 
you should just specify the result type to be Promise<MessageEmbed> for both instead

2023-09-19 22:51 UTC, tanndlin commented on src/app/slash_plugins/leaderboard.plugin.ts
> +const gameTypes = ['TicTacToe', 'ConnectFour'];
We should probably make this an enum instead of an array to avoid the gymanstics of getting the index and using that

2023-09-19 22:51 UTC, tanndlin commented on src/__tests__/alt.test-old.ts
> +// });
Let's just delete this

if we need it later we can checkout an older commit

2023-09-20 11:22 UTC, c650 approved these changes

2023-09-20 21:05 UTC, tanndlin approved these changes

2023-09-20 21:05 UTC, merged