feat: Convert Broadcast to slash command
cs-discord-at-ucf/lion pull request #805
Opened 2023-09-21 00:28 UTC by tanndlin

This PR is a 2 parter, but can be seperated if need be. I figured combining them, would simplify the code for broadcast since im already diffing it

 - Converts broadcast to slash command
 
 - Creates `createConfirmationReply` in `util.ts`
 
 `createConfirmationReply` replies to an interaction with a given payload and appends a confirm and cancel button.
 It handles the listening for events and calling the `onConfirm` and `onCancel` methods passed into original call`

2023-09-22 10:54 UTC, c650 approved these changes

2023-09-22 10:54 UTC, c650 commented on src/app/slash_plugins/broadcast.plugin.ts
> +        ...(attachment && { files: [attachment] }),
this syntax is lit

2023-09-22 10:54 UTC, c650 commented on src/common/utils.ts
> +  collector.on('end', async () => {
neat!

2023-09-22 17:57 UTC, suneettipirneni requested changes

2023-09-22 17:57 UTC, suneettipirneni commented on src/app/slash_plugins/addclasschans.plugin.ts
> +    await proceedToAddClasses(container, classes);
These can be done concurrently.
```suggestion
    await Promise.all([
        btnInteraction.followUp('Creating channels...'),
        proceedToAddClasses(container, classes),
    ]);
```

2023-09-28 17:06 UTC, tanndlin commented on src/common/utils.ts
> +    type: 1,
I used the MessageButton objects instead now, I had some weird error when trying to pass the JSON in with strings instead of magic numbers

2023-09-28 17:46 UTC, suneettipirneni approved these changes

2023-09-28 18:41 UTC, merged