Newest Item on Market displays first
cs-discord-at-ucf/lion pull request #831
Opened 2024-03-31 03:10 UTC by tanndlin

2024-03-31 18:20 UTC, CallumCoy approved these changes

2024-04-01 22:10 UTC, c650 requested changes

2024-04-01 22:10 UTC, c650 commented on src/app/commands/marketplace.command.ts
i think it makes more sense to put the listings in the correct order before chunking.

2024-04-01 22:30 UTC, tanndlin commented on src/app/commands/marketplace.command.ts
lol dont know why i didnt think of that

2024-04-01 22:33 UTC, c650 approved these changes

2024-04-01 22:33 UTC, c650 commented on src/app/commands/marketplace.command.ts
> +  // Reverse the result so that the newest item is the first page
this comment doesn't belong anymore?

2024-04-02 00:01 UTC, merged